# Generated by Django 5.0.4 on 2024-05-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('password_hash', models.CharField()),
                ('board_state', models.JSONField()),
            ],
        ),
    ]
