# Generated by Django 5.0.4 on 2024-05-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='lso',
            field=models.IntegerField(default=0),
        ),
    ]
